Metrics/LineLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false
