default: &default
  adapter: postgresql
  database: flashcards_app
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  timeout: 5000
  host: 192.168.1.6
  port: 5432

test:
  <<: *default
  database: travis_ci_test
