# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd2f797649c26278c2625bdb07c20874ae675f8f3dff30a0c5f7e2ce93873c35bdd289fcf3af608e63429e6dbadb1527e3c1b7964782f7caf37917819e180d86

test:
  secret_key_base: 12bac75ffb7e0dc8578914b6d8f3b4bd7f7b0e50b81966fc0523be1c8e7cd9fc42da2e38cd086480336ab911e104040043d3215779428dfc51b7094589dc1da3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
